---

info:
  id: model_hwh_v2_109

extract:
  - id: munged_data
    type: airflow
    dag_id: model_hot_water_heater_detection
    task_id: transform_hwh_109
    format: parquet

transform:
  type: task
  task: model_hwh_v2_109.ModelHWHv2
  script: model_hwh_v2_109.py
  report:
    type: datadog

load:
  type: file
  format: parquet
