---

info:
  id: sla_reporting_alliant
  owner: AMI-GOs
  email: beerd@tendrilinc.com

extract:
  - id: qc_output
    type: airflow
    dag_id: dag_alliant
    task_id: ami_qc

transform:
  type: task
  script: sla_reporting_alliant.py
  task: sla_reporting_alliant.AmiSlaReportingAlliant

load:
  type: file
  format: parquet
  repartition: 1
