---

info:
  id: transform_hwh_other

extract:
  - id: channels
    type: airflow
    dag_id: soa_daily
    task_id: transform_channels
    format: parquet
  - id: locations
    type: airflow
    dag_id: soa_daily
    task_id: transform_locations
    format: parquet
  - id: features_11
    type: airflow
    dag_id: model_ev_detection
    task_id: extract_features_11
    format: parquet
  - id: features_12
    type: airflow
    dag_id: model_ev_detection
    task_id: extract_features_12
    format: parquet
  - id: features_79
    type: airflow
    dag_id: model_ev_detection
    task_id: extract_features_79
    format: parquet
  - id: ws_ami
    type: airflow
    dag_id: model_electric_heat_detection
    task_id: model_weather_sensitivity_ami
    format: parquet
  - id: experian
    type: airflow
    dag_id: demographics_matching_v2
    task_id: transform_match_demographics
    format: parquet
  - id: location_profiles_tabular
    type: airflow
    dag_id: tendril
    task_id: transform_location_profiles_tabular
    format: parquet
  - id: wh_score
    type: airflow
    dag_id: model_hot_water_heater_detection
    task_id: hot_water_heater
    format: parquet

transform:
  type: task
  task: transform_hwh_other.TransformHWH
  script: transform_hwh_other.py

load:
  type: file
  format: parquet
