---

info:
  id: model_weather_sensitivity
  owner: Erica Swanson, Joe Wofford
  email: eswanson@tendrilinc.com

extract:
  - id: bills
    type: airflow
    dag_id: soa_daily
    task_id: transform_bills
    format: parquet
  - id: locations
    type: airflow
    dag_id: soa_daily
    task_id: transform_locations
    format: parquet
  - id: channels
    type: airflow
    dag_id: soa_daily
    task_id: transform_channels
    format: parquet
  - id: weather
    type: airflow
    dag_id: weather
    task_id: transform_historical_weather_daily
    format: parquet

transform:
  type: script
  script: script.py

load:
  type: file
  format: parquet
