---

info:
  id: model_hvac_upgrade_propensity
  owner: Ihno Lee, Erica Swanson
  email: ilee@tendrilinc.com

extract:
  - id: experian_normalized
    type: airflow
    dag_id: demographics_matching
    task_id: transform_normalize_experian
    format: parquet
  - id: accounts
    type: airflow
    dag_id: soa_daily
    task_id: transform_accounts
    format: parquet
  - id: locations
    type: airflow
    dag_id: soa_daily
    task_id: transform_locations
    format: parquet
  - id: weather_sensitivity
    type: airflow
    dag_id: models
    task_id: transform_weather_sensitivity
    format: parquet
  - id: kcpl
    type: file
    static: kcpl_participation_hvac
    format: csv
    options:
      header: true


transform:
  type: task
  script: task.py
  task: task.HVACUpgradePropensity
  report:
    type: datadog

load:
  type: file
  format: parquet
